apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: realestaterag
  app.kubernetes.io/version: "1.0.0"

namespace: default
